Repository Guardians-DSC/Front-HoCo, pull requests merged in 2022-06, with the labels that each got.

#46 Ref add background menu
  package-lock.json
  src/components/Menu/index.js
  src/components/Menu/style.js
Labels: :gear: enhancement

#47 align answers and add link to image that doesn't work
  README.md
  src/components/Question/style.js
  src/views/Duvidas/Data.js
Labels: Refactor

#44 Fix #43: Activities Page
  package.json
  src/components/ActivitiesTable/index.js
  src/components/ActivitiesTable/style.js
  src/components/ActivityModal/index.js
  src/components/ActivityModal/style.js
  src/components/EditActivityCell/index.js
  src/contexts/activities.context.js
  src/index.js
  src/views/Atividades/index.js
  yarn.lock
Labels: :lady_beetle: bug

#48 Ref - Add organization api route
  src/assets/icons/Loading/index.js
  src/assets/icons/Loading/styles.js
  src/components/Organizations/OrganizationCard/style.js
  src/components/Organizations/index.js
  src/components/Organizations/style.js
  src/contexts/app.context.js
  src/services/api.js
  src/styles/base-styles.js
  src/views/Organizacoes/index.js
Labels: :gear: enhancement
